name: maven-build

on:
  pull_request:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
    types: [ assigned ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify:
    secrets: inherit
    uses: dangernoodle-io/.github/.github/workflows/maven.yml@main
    with:
      maven-goals: verify
