name: maven-release

on:
  workflow_dispatch:

jobs:
  build-main:
    secrets: inherit
    uses: dangernoodle-io/.github/.github/workflows/maven.yml@main
    with:
      maven-goals: release:prepare release:perform
      release: true
